---
- name: Install apt packages and tools
  become: true
  ansible.builtin.apt:
    name:
      - git
      - golang-go
      - python3-venv
      - gcc
      - libpcap-dev
      - libusb-1.0-0-dev
      - libnetfilter-queue-dev
      - apparmor
      - metasploit-framework
      - postgresql
      - ufw
      - feroxbuster
    state: present
  register: apt_packages
  until: apt_packages is success
  retries: 2
  delay: 3

- name: Install other tools
  ansible.builtin.include_tasks: "{{ tool_task }}"
  loop: "{{ lookup('fileglob', 'tools/*.yaml', wantlist=True) }}"
  loop_control:
    loop_var: tool_task
