---
- name: Create the default Kali user
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"
    groups: sudo
    shell: "/bin/{{ shell }}"
    createhome: true
    ssh_key_type: ed25519
    ssh_key_bits: 4096
    ssh_key_passphrase: "{{ password }}"

- name: Add the Golang bin folder to PATH
  become: true
  become_user: "{{ username }}"
  lineinfile:
    path: "~/.{{ shell }}rc"
    line: "export PATH=${PATH}:~/go/bin"
